// coffee-machine-react/src/infrastructure/DrinkMakerBox/DrinkMakerBox.js
import React from 'react';
import NullComponent from "./components/NullComponent";
import ShowDrink from "./components/ShowDrink";
import {isValidCommand} from "./validator/isValidCommand";
import {drinkMaker} from '../drinkMaker';

import './drink-maker-box.css';

function DrinkMakerBox({command = ''}) {
    if (!isValidCommand(command)) {
        return <NullComponent/>
    }

    drinkMaker.execute(command);

    return <ShowDrink command={command}/>
}


export default DrinkMakerBox;

// coffee-machine-vue/src/infrastructure/DrinkMakerBox.vue
<template>
  <div class="drink-maker-box">
    <ShowDrink v-if="isValidCommand()" :command="command"></ShowDrink>
    <NullComponent v-else></NullComponent>
  </div>
</template>

<script>
import NullComponent from './DrinkMakerBox/components/NullComponent.vue';
import ShowDrink from './DrinkMakerBox/components/ShowDrink.vue';
import { isValidCommand } from './DrinkMakerBox/validator/isValidCommand';
import { drinkMaker } from './drinkMaker';

export default {
  name: 'DrinkMakerBox',
  components: {
    NullComponent,
    ShowDrink,
  },
  props: {
    command: {
      type: String,
      default: '',
    },
  },
  methods: {
    isValidCommand: function() {
      if (!this.$props.command) return false;

      if (isValidCommand(this.$props.command)) {
        return false
      }

      drinkMaker.execute(this.$props.command)
      return true;
    }
  },
};
</script>
