// coffee-machine-react/src/components/machine/Wrapper.js
import React from 'react';
import CoffeeCup from '../coffee/CoffeeCup';

import './wrapper.css';

function MachineWrapper({ children }) {
  return (
    <div className="machine">
      <div className="machine-top-container">
        <div className="machine-top"></div>
      </div>
      <div className="cup-wrapper">
        <CoffeeCup />
      </div>
      <div className="drink-maker">{children}</div>
    </div>
  );
}

export default MachineWrapper;

// coffee-machine-vue/src/ui/machine/Wrapper.vue
<template>
  <div class="machine">
    <div class="machine-top-container">
      <div class="machine-top"></div>
    </div>
    <div class="cup-wrapper">
      <CoffeeCup />
    </div>
    <div class="drink-maker">
      <slot></slot>
    </div>
  </div>
</template>

<script>

import CoffeeCup from "../coffee/CoffeeCup.vue";

export default {
  name: 'MachineWrapper',
  components: {
    CoffeeCup,
  },
};
</script>

<style>
@import './wrapper.css';
</style>
