// coffee-machine-react/src/infrastructure/DrinkMakerBox/components/MessageBox.js
function MessageBox({ text }) {
    return (
        <div className="container">
            <div className="arrow">
                <div className="outer"></div>
                <div className="inner"></div>
            </div>
            <div className="message-body">
                <p>{text}</p>
            </div>
        </div>
    );
}

export default MessageBox;

// coffee-machine-vue/src/infrastructure/DrinkMakerBox/components/MessageBox.vue
<template>
  <div class="container">
    <div class="arrow">
      <div class="outer"></div>
      <div class="inner"></div>
    </div>
    <div class="message-body">
      <p>{{ text }}</p>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    text: {
      type: String,
      required: true,
    },
  },
};
</script>

<style>
/* Add your CSS styles here */
</style>
