// coffee-machine-react/src/components/coin/InsertCoin.js
import React, { useState } from 'react';

import './insert-coin.css';

function InsertCoin({ onInsertedCoin }) {
  const [insertedCoins, setInsertedCoins] = useState('');

  const handleOnChange = (ev) => {
    const insertedCoin = ev.target.value;
    setInsertedCoins(insertedCoin);
    onInsertedCoin(insertedCoin);
  };

  return (
    <div>
      <input
        type="number"
        className="input"
        min="0"
        max="100"
        value={insertedCoins}
        onChange={handleOnChange}
        placeholder="Insert Coin"
      />
    </div>
  );
}

export default InsertCoin;

// coffee-machine-vue/src/ui/coin/InsertCoin.vue
<template>
  <div>
    <input
      type="number"
      class="input"
      min="0"
      max="100"
      :value="insertedCoins"
      @change="handleOnChange"
      placeholder="Insert Coin"
    />
  </div>
</template>

<script>
export default {
  name: 'InsertCoin',
  data() {
    return {
      insertedCoins: '',
    };
  },
  methods: {
    handleOnChange(event) {
      const insertedCoin = event.target.value;
      this.insertedCoins = insertedCoin;
      this.$emit('onInsertedCoin', insertedCoin);
    },
  },
};
</script>

<style>
@import './insert-coin.css';
</style>
