// coffee-machine-vue/src/ui/buttons/Button.vue
<template>
  <button @click="onClick" :class="['button', { 'small': small }]">
    {{ text }}
  </button>
</template>

<script>
export default {
  name: 'Button',
  props: {
    text: {
      type: String,
      required: true,
    },
    onClick: {
      type: Function,
      default: () => {},
    },
    small: {
      type: Boolean,
      default: false,
    },
  },
};
</script>

<style>
@import './button.css';
</style>

// coffee-machine-react/src/components/buttons/Button.js
import React from 'react';
import PropTypes from 'prop-types';

import './button.css';

function Button({ text, onClick, small }) {
  return (
    <button
      onClick={() => {
        onClick(text);
      }}
      className={`button ${small ? 'small' : ''}`}
    >
      {text}
    </button>
  );
}

Button.propTypes = {
  text: PropTypes.string.isRequired,
  onClick: PropTypes.func.isRequired,
  small: PropTypes.bool,
};

export default Button;
