// coffee-machine-react/src/components/buttons/ColumnsButtonsGroup.js
import React, { useState } from 'react';

import './columns-buttons-group.css';

function ButtonsGroup({ children }) {
  const childrens = React.Children.toArray(children);
  const [selectedButton, setSelectedButton] = useState('');

  // This is just for "hiding complexity" to developers who are learning TDD
  // It's not a good practice to use it in a production code
  const handleClick = (event) => {
    const target = event.target;
    const classNames = target.className || '';

    if (classNames.includes('button')) {
      const text = target.textContent;
      setSelectedButton(text);
    }
  };

  return (
    <ul className="button-group">
      {childrens.map((child, index) => {
        const childText = child.props.text;
        return (
          <li
            key={index}
            onClick={handleClick}
            className={childText === selectedButton ? 'is-selected' : ''}
          >
            {child}
          </li>
        );
      })}
    </ul>
  );
}

export default ButtonsGroup;

// coffee-machine-vue/src/ui/buttons/ColumnsButtonsGroup.vue
<template>
  <ul class="button-group">
    <li
      v-for="(child, index) in childrens"
      :key="index"
      @click="handleClick"
      :class="{'is-selected': child.props.text === selectedButton}"
    >
      <slot :name="child.props.name"></slot>
    </li>
  </ul>
</template>

<script>
import {ref} from 'vue';

export default {
  name: 'ButtonsGroup',
  props: {
    children: {
      type: Array,
      required: true,
    },
  },
  setup(props) {
    const childrens = ref([]);
    const selectedButton = ref('');

    // Initialize childrens with a ref value
    childrens.value = props.children;

    const handleClick = (event) => {
      const target = event.target;
      const classNames = target.className || '';

      if (classNames.includes('button')) {
        selectedButton.value = target.textContent;
      }
    };

    return {
      childrens,
      selectedButton,
      handleClick,
    };
  },
};
</script>

<style scoped>
@import './columns-buttons-group.css';
</style>
