// coffee-machine-vue/src/CoffeeMachine.vue
<template>
  <MachineWrapper>
    <DrinksBlock>
      <ColumnsButtonsGroup>
<!--        Please read the README to see the available React components.-->
      </ColumnsButtonsGroup>
    </DrinksBlock>

    <RightPanel>
      <p>This is the right panel</p>
    </RightPanel>

    <div class="output">
      <DrinkMakerBox :command="command" />
    </div>
  </MachineWrapper>
</template>

<script>
import DrinksBlock from './ui/machine/DrinksBlock.vue';
import ColumnsButtonsGroup from './ui/buttons/ColumnsButtonsGroup.vue';
import RightPanel from './ui/machine/RightPanel.vue';
import CoffeeCup from "./ui/coffee/CoffeeCup.vue";
import MachineWrapper from "./ui/machine/Wrapper.vue";
import Button from "./ui/buttons/Button.vue";
import DrinkMakerBox from "./infrastructure/DrinkMakerBox.vue";

export default {
  components: {
    MachineWrapper,
    CoffeeCup,
    DrinksBlock,
    ColumnsButtonsGroup,
    RightPanel,
    Button,
    DrinkMakerBox
  },
  data() {
    return {
      command: ''
    };
  },
  methods: {
    handleClick() {
    },
  }
}
</script>

<style>
/* Add CSS styles here */
</style>

// coffee-machine-react/src/CoffeeMachine.js
import React, { useState } from 'react';
import DrinkMakerOutput from './infrastructure/DrinkMakerOutput';
import MachineWrapper from './ui/machine/Wrapper';
import DrinksBlock from './ui/machine/DrinksBlock';
import ColumnsButtonsGroup from './ui/buttons/ColumnsButtonsGroup';
import RightPanel from './ui/machine/RightPanel';

function CoffeeMachine() {
  const [command, setCommand] = useState('');

  return (
    <MachineWrapper>
      <DrinksBlock>
        <ColumnsButtonsGroup>
          {/*Please read the README to see the available React ui.  */}
        </ColumnsButtonsGroup>
      </DrinksBlock>

      <RightPanel>
        <p>This is the right panel</p>
      </RightPanel>

      <div className="output">
        <DrinkMakerOutput command={command} />
      </div>
    </MachineWrapper>
  );
}

export default CoffeeMachine;
